apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 726782493526.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 726782493526.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 0ab52bc4
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
